### ISSUE TITLE
How to Run?

### ISSUE THREAD

**Issue by esotericsean** [PrawnCocktail/MSTV#1]
Sorry, this isn't really an issue, but didn't see any other way to contact you.

Really want to get this working, but I'm not sure how to compile it. Do I just open the .sln in Visual Studio and hit run?

**Comment by PrawnCocktail** [comment]
Hey, 
If you want to compile it and run it, yeah just open the sln in visual studio and press the start button at the top https://i.imgur.com/xBznQky.png

or just download the prebuilt version from the releases section
https://github.com/PrawnCocktail/MSTV/releases/download/v1.0/MSTV.exe

**Comment by esotericsean** [comment]
Ah, thanks! Didn't see the releases section. But glad to know I was on the right track. Really appreciate you taking the time to make this tool!
