### ISSUE TITLE
406 Not Acceptable

### ISSUE THREAD

**Issue by esotericsean** [PrawnCocktail/MSTV#2]
So I've downloaded over 1200 episodes now and it's been working great! I do occasionally get the error 422, but all of a sudden it started giving me error 422 seemingly permanently (I left it for 20-25 minutes and just kept displaying that error).

On the same computer, when I try logging into the marthastewart.tv website, I now get a 406 Not Acceptable error. I can still browse and play episodes, so it's acting as if I'm logged in, but can't view my account page.

I can still log in on another computer just fine, so I'm wondering if there's some sort of cache that I need to reset. Maybe restarting my computer will help. For a moment I was afraid they banned my account.

Anyway, not sure if this info is helpful in any way. Thanks again for your hard work!

**Comment by esotericsean** [comment]
Update: Restarting fixed the issue. 🤷🏻‍♂️

**Comment by PrawnCocktail** [comment]
Holy cow, 1200 episodes already, nice to see it being used so much :) 

I'm not sure why it would give so many 422 errors, i think the most i got was 5 or 6.  
It might be that your logging into the site so many times that the server is having to limit logins. 
I'm still trying to figure out the reason for the 422 error in the first place, but not having much luck. 

Glad to hear you fixed the issue, i assume it was just a cache issue, strange though.

**Comment by esotericsean** [comment]
Thanks again for making this! Do you have a way I can donate to you? I've been looking to download this show for years and years and now that it's finally available, your app helped me download every available episode. :)

**Comment by PrawnCocktail** [comment]
I had never watched Martha until I saw your reddit post, then I was working on this tool and I cant believe I missed it all these years, I'm really enjoying it, So thank you for that :smile: 

I really appreciate the offer of a donation, but its not expected in any way. 
But if you REALLY want to, then send me a DM on reddit (I was the one who sent you the link to this repository) 
 
I'm just happy you managed to get everything you needed :smile:
